### ISSUE TITLE
Microsoft Authentication Failed: 404

### ISSUE THREAD

**Issue by af280cf94190a54043e947948a0031ce7ed71dc** [tropicbliss/buckshot#14]
Not sure what's returning a 404 but when trying to GC snipe it's giving 404

**Comment by tropicbliss** [comment]
1. Download the latest release. I closed down my authentication server (to save costs + transparency that I"m not doing anything nefarious with your account information), and have embedded the code in the sniper itself.
2. You have to unfortunately delete your old config file and let the sniper generate a new one. The new config file is incompatible with the previous one. Ask below if you have any questions 👍
3. Also the new version allows for multi account gc sniping, so you might find that feature useful.
