### ISSUE TITLE
Offset issue

### ISSUE THREAD

**Issue by Customcrop** [tropicbliss/buckshot#17]
I can't set my own offset i removed the # at the start of the line and i puttted my offset but it still sets a different delay a negative delay. Maybe i am dumb and i am doing it wrong or something like that?!

**Comment by tropicbliss** [comment]
Created a [guide](https://github.com/tropicbliss/buckshot/blob/main/CONFIG.md) for the config file. See if that can resolve your issue. Maybe re-download if you are on an earlier version.

**Comment by tropicbliss** [comment]
Also feel free to paste your config file here while redacting your email and password. Make sure your config file is named `config.toml`.

**Comment by Customcrop** [comment]
Yep i fixed the issue with the guide u made thank u very much!
