### ISSUE TITLE
Sniper fails on drop time

### ISSUE THREAD

**Issue by oliver408i** [tropicbliss/buckshot#20]
It just stops on the drop time and throws an error
```
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'Read timeout: Elapsed(())Read timeout: Elapsed(())', ', src/sockets.rssrc/sockets.rs::88:8822:
22note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Error: Failed to execute the snipe of xqv

Caused by:
    panic```

**Comment by tropicbliss** [comment]
Interesting. Good news is that I think I know what causes the error. Lemme try to fix it for you

**Comment by tropicbliss** [comment]
Alright, I simply raised the timeout time. Download the latest release [here](https://github.com/tropicbliss/buckshot/releases/tag/v4.0.7). Comment here if there is any more issues

**Comment by oliver408i** [comment]
Alright, will test tomorrow when I have a name I wanna snipe

**Comment by oliver408i** [comment]
Alright, the console cleared on the vps where I was doing the snipe, and I didn't snipe it. I am not sure what happened, but if the error comes again, I will open another issue. (I don't plan on sniping anything right now) Thanks...

**Comment by oliver408i** [comment]
Is the timeout thingy affecting how good the sniper is? It seems like the chance of snipe is lower than what I used to have. The names have around the same popularity
