### ISSUE TITLE
Newest version snipes nothing

### ISSUE THREAD

**Issue by oliver408i** [tropicbliss/buckshot#21]
In an older version, I sniped a name on my 2nd try. Currently, I am using same machine, same offset, and after ~10 names, none of them was sniped. I think this might be a problem with the new update mentioned in → #20

**Comment by tropicbliss** [comment]
In #20 I tried to lengthen the timeout required for the sniper to receive info back from the server. It was originally set to 5 seconds but I set it to 27 seconds just in case Mojang api acts up a bit. Does the sniper still panic or does it simply say that the snipe failed?

**Comment by oliver408i** [comment]
failed, very time for (now) 12 or 13 names. Looks like the error codes all say 429, almost no 403s. Is this a problem with my offset? I am using a VPS, so maybe the offset changed?

**Comment by oliver408i** [comment]
No it does not panic

**Comment by oliver408i** [comment]
Also, I'm trying to use a different offset now, and I calculated the response time to be 0:00:00.132698.5  on average. What value should I enter for offest?

**Comment by tropicbliss** [comment]
That's so weird. Perhaps I will remove the timeout because that's the only thing I've changed

**Comment by oliver408i** [comment]
Yea, I am sniping for my friend and we are all ready to give up...

**Comment by tropicbliss** [comment]
Alright. Try this final version right [here](https://github.com/tropicbliss/buckshot/releases/tag/v4.0.8). I no longer snipe anymore so I have no idea whether this shit works or not

**Comment by oliver408i** [comment]
Ok I'll try, again. Also what would be my offset?

**Comment by tropicbliss** [comment]
It is region dependent. I would have no idea what your ideal offset should be though if you were renting a vps in the new york-ashburn area it should be in the ballpark of 10ms

**Comment by oliver408i** [comment]
Ok but is it normal if the offset I got was 135 ms?

**Comment by tropicbliss** [comment]
Perfectly fine
