### ISSUE TITLE
HTTP status code 500

### ISSUE THREAD

**Issue by bitchery** [tropicbliss/buckshot#4]
![image](https://user-images.githubusercontent.com/87142512/125105974-ff8d3700-e0d6-11eb-8667-88b96f2423e8.png)

Sorry to be making a new issue here but, there seems to be a problem!

**Comment by tropicbliss** [comment]
Alright try again, this time issue should reeealy be fixed. As you can guess, this issue has nothing to do with the sniper and has everything to do with my API that likes to shit itself.

**Comment by bitchery** [comment]
Seems all good now.

Thanks for the help!
