### ISSUE TITLE
? Error

### ISSUE THREAD

**Issue by gentuwu** [tropicbliss/buckshot#5]
Basically i log into my minecraft account using my microsoft account, and i sign into there with my github. i start it up and it says i did not enter a password/username yet it says its not needed in config.toml.

**Comment by tropicbliss** [comment]
Okay that is some historical stuff that I forgot to remove in config.toml. Basically you need to enter the username and password in the config file now. I will change it.

**Comment by gentuwu** [comment]
> Okay that is some historical stuff that I forgot to remove in config.toml. Basically you need to enter the username and password in the config file now. I will change it.

well when i did enter it, it said it was the wrong password when it wasn't.

**Comment by gentuwu** [comment]
> > Okay that is some historical stuff that I forgot to remove in config.toml. Basically you need to enter the username and password in the config file now. I will change it.
> 
> well when i did enter it, it said it was the wrong password when it wasn't.

nevermind! i see you fixed this good stuff man
