### ISSUE TITLE
[MicroAuth] HTTP status code: 403 Please try again later.

### ISSUE THREAD

**Issue by etz** [tropicbliss/buckshot#6]
Using the latest maintenance build, I am experiencing a 403 error after attempting to start the application. Waited approximately 1 hour and tried again to no avail. I am able to use the Mojang API to check available usernames, not quite sure why access is being forbidden (potentially something to do with a MS account?). Config below.

config.toml
```
[account]
username = "my_email@outlook.com"
password = "my_password"
# Leave the rest empty if you do not have security questions
sq1 = ""
sq2 = ""
sq3 = ""

[config]
offset = 0
auto_offset = false
spread = 0
microsoft_auth = true
gc_snipe = true
change_skin = false
skin_model = "slim"
skin_filename = "example.png"
# Name queueing example:
# name_queue = ["Marc", "Dream"]
name_queue = ["Marc", "Dream"]
```

**Comment by tropicbliss** [comment]
Marc Dream are just example usernames. Don't tell me you wanna snipe the username Dream.

**Comment by tropicbliss** [comment]
Do you live in the US or Japan. I'm checking Cloudflare logs because it is blocking your ip for some reason.

**Comment by tropicbliss** [comment]
Alright it's my fault. I misconfigured the firewall for my API. Try again, I'm terribly sorry.

**Comment by etz** [comment]
Seems to be working now. Thank you.
