### ISSUE TITLE
Sniper closes after entering name I want to snipe.

### ISSUE THREAD

**Issue by OysterSniper** [tropicbliss/buckshot#9]
I installed everything, edited config and when I enter the name I want to snipe, programm closes automaticaly. Am I doing something wrong or its sniper's issue?

**Comment by tropicbliss** [comment]
Type in the command from the terminal, don't double-click to open file.

**Comment by OysterSniper** [comment]
Now Im getting these error but credentials are right
![image](https://user-images.githubusercontent.com/89070972/129910517-154fb168-88ef-4a5b-b5fc-ffb80f1f99c7.png)

**Comment by tropicbliss** [comment]
Do you enter the answers of your security questions? Also maybe redownload the latest release I might have fixed something

**Comment by tropicbliss** [comment]
Closed due to inactivity
